module "birju_vm" {
  source               = "../azurerm_virtual_machine"
  resource_group_name  = "rg-todoapp"
  location             = "Central India"
  vm_name              = "birjuvm"
  vm_size              = "Standard_DS2V2"
  image_publisher      = "ubuntu"
  image_offer          = "ubuntu"
  image_sku            = "v2"
  image_version        = "v1"
  nic_name             = "birju-nic"
  virtual_network_name = "birju_vnet"
  subnet_name          = "tilu_subnet"
  username_secret_name = "birju-username"
  password_secret_name = "birju-password"
  key_vault_name       = "birjukitijori"
}

module "tirju_vm" {
  source               = "../azurerm_virtual_machine"
  resource_group_name  = "rg-todoapp"
  location             = "Central India"
  vm_name              = "tirjuvm"
  vm_size              = "Standard_DS2V2"
  image_publisher      = "ubuntu"
  image_offer          = "ubuntu"
  image_sku            = "v2"
  image_version        = "v1"
  nic_name             = "tirju-nic"
  virtual_network_name = "tirju_vnet"
  subnet_name          = "frontend_subnet"
  username_secret_name = "birju-username"
  password_secret_name = "birju-password"
  key_vault_name       = "birjukitijori"
}
